spring:
  rabbitmq:
    host: localhost
    port: 5672
    username : guest
    password: guest

rabbitmq:
  fanout:
    exchange: fanout.exchange
    queue: fanout.queue.2
  topic:
    exchange: topic.exchange
    queue: topic.queue.2
    key: topic2.#
  headers:
    exchange: header.exchange
    queue: header.queue.2
server:
  port: 8081
