spring:
  rabbitmq:
    host: localhost
    port: 5672
    username : guest
    password: guest

rabbitmq:
  fanout:
    exchange: fanout.exchange
    queue: fanout.queue.1
  topic:
    exchange: topic.exchange
    queue: topic.queue.1
    key: topic1.#
  headers:
    exchange: header.exchange
    queue: header.queue.1
server:
  port: 8080
